[package]
name = "@os20/physical"
version = "0.1.0"
edition = "2026"
role = "ontology"

[dependencies]
engineering = "@os20/engineering@^0.1"
physics = "@os20/physics@^0.1"
electrical = "@os20/electrical@^0.1"
