//! Canonical OS20 relation vocabulary (authored vs derived).
//!
//! UIDS/OS20 identity already owns `Specialize`, `Mixin`, `Extend`, `Compose`.
//! Those are not redeclared here.

use crate::identity::PredicateId;

/// Whether a relation is stored or inferred.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum RelationAuthorship {
    /// Written on the engineering graph.
    Authored,
    /// Computed from an authored inverse or traversal.
    Derived,
}

/// One canonical OS20 engineering relation.
#[derive(Clone, Copy, Debug)]
pub struct RelationDecl {
    /// Stable id (`@os20/engineering#instanceOf` or frozen `@os20/core#contains`).
    pub id: &'static str,
    /// Local name.
    pub name: &'static str,
    /// Source classifier (named id).
    pub source: &'static str,
    /// Target classifier.
    pub target: &'static str,
    /// Cardinality note.
    pub cardinality: &'static str,
    /// Transitive?
    pub transitive: bool,
    /// Symmetric?
    pub symmetric: bool,
    /// Inverse id, if any.
    pub inverse: Option<&'static str>,
    /// Authored or derived.
    pub authorship: RelationAuthorship,
    /// Cycle rule.
    pub cycles: &'static str,
    /// v1 status.
    pub v1: bool,
    /// Short example.
    pub example: &'static str,
}

/// Frozen core containment — reuse, do not fork.
pub const CONTAINS: &str = "@os20/core#contains";

/// Look up a canonical relation by local name or full id.
pub fn relation(name: &str) -> Option<&'static RelationDecl> {
    canonical_relations()
        .iter()
        .find(|r| r.name == name || r.id == name)
}

/// Predicate id for a canonical relation.
pub fn relation_id(name: &str) -> PredicateId {
    let decl = relation(name).unwrap_or_else(|| panic!("unknown relation {name}"));
    PredicateId::new(decl.id).expect("canonical relation id")
}

/// Foundational OS20 relations (Specialize is owned by the identity substrate).
pub fn canonical_relations() -> &'static [RelationDecl] {
    RELATIONS
}

const RELATIONS: &[RelationDecl] = &[
    RelationDecl {
        id: "@os20/engineering#instanceOf",
        name: "instanceOf",
        source: "@os20/engineering#EngineeringInstance",
        target: "@os20/engineering#EngineeringDefinition",
        cardinality: "1",
        transitive: false,
        symmetric: false,
        inverse: Some("@os20/engineering#instantiates"),
        authorship: RelationAuthorship::Authored,
        cycles: "forbidden (not a type lattice)",
        v1: true,
        example: "TractionMotor instanceOf TractionMotorDefinition",
    },
    RelationDecl {
        id: "@os20/engineering#instantiates",
        name: "instantiates",
        source: "@os20/engineering#EngineeringDefinition",
        target: "@os20/engineering#EngineeringInstance",
        cardinality: "*",
        transitive: false,
        symmetric: false,
        inverse: Some("@os20/engineering#instanceOf"),
        authorship: RelationAuthorship::Derived,
        cycles: "n/a",
        v1: true,
        example: "TractionMotorDefinition instantiates TractionMotor",
    },
    RelationDecl {
        id: CONTAINS,
        name: "contains",
        source: "@os20/core#Thing",
        target: "@os20/core#Thing",
        cardinality: "*",
        transitive: true,
        symmetric: false,
        inverse: Some("@os20/engineering#partOf"),
        authorship: RelationAuthorship::Authored,
        cycles: "forbidden",
        v1: true,
        example: "EVPowertrain contains TractionMotor",
    },
    RelationDecl {
        id: "@os20/engineering#partOf",
        name: "partOf",
        source: "@os20/core#Thing",
        target: "@os20/core#Thing",
        cardinality: "0..1",
        transitive: true,
        symmetric: false,
        inverse: Some(CONTAINS),
        authorship: RelationAuthorship::Derived,
        cycles: "forbidden (inverse of contains)",
        v1: true,
        example: "TractionMotor partOf EVPowertrain",
    },
    RelationDecl {
        id: "@os20/engineering#hasProperty",
        name: "hasProperty",
        source: "@os20/core#Thing",
        target: "@os20/engineering#EngineeringProperty",
        cardinality: "*",
        transitive: false,
        symmetric: false,
        inverse: None,
        authorship: RelationAuthorship::Authored,
        cycles: "n/a",
        v1: true,
        example: "TractionMotor hasProperty RatedTorque",
    },
    RelationDecl {
        id: "@os20/engineering#hasGeometry",
        name: "hasGeometry",
        source: "@os20/engineering#PhysicalInstance",
        target: "@os20/physical#Geometry",
        cardinality: "*",
        transitive: false,
        symmetric: false,
        inverse: None,
        authorship: RelationAuthorship::Authored,
        cycles: "n/a",
        v1: true,
        example: "TractionMotor hasGeometry TractionMotorGeometry",
    },
    RelationDecl {
        id: "@os20/engineering#hasBehavior",
        name: "hasBehavior",
        source: "@os20/core#Thing",
        target: "@os20/engineering#BehaviorDefinition",
        cardinality: "*",
        transitive: false,
        symmetric: false,
        inverse: None,
        authorship: RelationAuthorship::Authored,
        cycles: "n/a",
        v1: true,
        example: "TractionMotor hasBehavior MotorBehavior",
    },
    RelationDecl {
        id: "@os20/engineering#madeOf",
        name: "madeOf",
        source: "@os20/engineering#PhysicalInstance",
        target: "@os20/physical#MaterialDefinition",
        cardinality: "0..1",
        transitive: false,
        symmetric: false,
        inverse: None,
        authorship: RelationAuthorship::Authored,
        cycles: "n/a",
        v1: true,
        example: "MotorHousing madeOf ElectricalSteel",
    },
    RelationDecl {
        id: "@os20/engineering#hasMaterialAssignment",
        name: "hasMaterialAssignment",
        source: "@os20/engineering#PhysicalInstance",
        target: "@os20/physical#MaterialAssignment",
        cardinality: "*",
        transitive: false,
        symmetric: false,
        inverse: None,
        authorship: RelationAuthorship::Authored,
        cycles: "n/a",
        v1: true,
        example: "TractionMotor hasMaterialAssignment StatorCopperAssign",
    },
    RelationDecl {
        id: "@os20/engineering#appliesToRegion",
        name: "appliesToRegion",
        source: "@os20/physical#MaterialAssignment",
        target: "@os20/physical#GeometricEntity",
        cardinality: "0..1",
        transitive: false,
        symmetric: false,
        inverse: None,
        authorship: RelationAuthorship::Authored,
        cycles: "n/a",
        v1: true,
        example: "StatorCopperAssign appliesToRegion StatorRegion",
    },
    RelationDecl {
        id: "@os20/engineering#hasPort",
        name: "hasPort",
        source: "@os20/core#Thing",
        target: "@os20/engineering#PortInstance",
        cardinality: "*",
        transitive: false,
        symmetric: false,
        inverse: None,
        authorship: RelationAuthorship::Authored,
        cycles: "n/a",
        v1: true,
        example: "TractionMotor hasPort ShaftPort",
    },
    RelationDecl {
        id: "@os20/engineering#connects",
        name: "connects",
        source: "@os20/engineering#ConnectionInstance",
        target: "@os20/engineering#PortInstance",
        cardinality: "2",
        transitive: false,
        symmetric: false,
        inverse: Some("@os20/engineering#connectedTo"),
        authorship: RelationAuthorship::Authored,
        cycles: "connection graph may be cyclic; composition must not",
        v1: true,
        example: "ShaftCoupling connects ShaftPort",
    },
    RelationDecl {
        id: "@os20/engineering#connectedTo",
        name: "connectedTo",
        source: "@os20/engineering#PortInstance",
        target: "@os20/engineering#PortInstance",
        cardinality: "*",
        transitive: false,
        symmetric: true,
        inverse: None,
        authorship: RelationAuthorship::Derived,
        cycles: "allowed",
        v1: true,
        example: "ShaftPort connectedTo GearboxInputPort",
    },
    RelationDecl {
        id: "@os20/engineering#realizes",
        name: "realizes",
        source: "@os20/core#Thing",
        target: "@os20/engineering#EngineeringDefinition",
        cardinality: "*",
        transitive: false,
        symmetric: false,
        inverse: None,
        authorship: RelationAuthorship::Authored,
        cycles: "n/a",
        v1: true,
        example: "FirmwareImage realizes MotorControllerSoftware",
    },
    RelationDecl {
        id: "@os20/engineering#implements",
        name: "implements",
        source: "@os20/software#SoftwareComponent",
        target: "@os20/engineering#InterfaceDefinition",
        cardinality: "*",
        transitive: false,
        symmetric: false,
        inverse: None,
        authorship: RelationAuthorship::Authored,
        cycles: "n/a",
        v1: true,
        example: "MotorFirmware implements MotorControlApi",
    },
    RelationDecl {
        id: "@os20/engineering#requires",
        name: "requires",
        source: "@os20/core#Thing",
        target: "@os20/core#Thing",
        cardinality: "*",
        transitive: false,
        symmetric: false,
        inverse: None,
        authorship: RelationAuthorship::Authored,
        cycles: "configuration requires must be acyclic",
        v1: true,
        example: "AWDOption requires PerformanceMotorOption",
    },
    RelationDecl {
        id: "@os20/engineering#allocatedTo",
        name: "allocatedTo",
        source: "@os20/assurance#RequirementDefinition",
        target: "@os20/core#Thing",
        cardinality: "*",
        transitive: false,
        symmetric: false,
        inverse: Some("@os20/engineering#hasAllocatedRequirement"),
        authorship: RelationAuthorship::Authored,
        cycles: "n/a",
        v1: true,
        example: "TorqueRequirement allocatedTo TractionMotor",
    },
    RelationDecl {
        id: "@os20/engineering#hasAllocatedRequirement",
        name: "hasAllocatedRequirement",
        source: "@os20/core#Thing",
        target: "@os20/assurance#RequirementDefinition",
        cardinality: "*",
        transitive: false,
        symmetric: false,
        inverse: Some("@os20/engineering#allocatedTo"),
        authorship: RelationAuthorship::Derived,
        cycles: "n/a",
        v1: true,
        example: "TractionMotor hasAllocatedRequirement TorqueRequirement",
    },
    RelationDecl {
        id: "@os20/engineering#refines",
        name: "refines",
        source: "@os20/assurance#RequirementDefinition",
        target: "@os20/assurance#RequirementDefinition",
        cardinality: "*",
        transitive: true,
        symmetric: false,
        inverse: None,
        authorship: RelationAuthorship::Authored,
        cycles: "forbidden",
        v1: true,
        example: "PeakTorqueRequirement refines TorqueRequirement",
    },
    RelationDecl {
        id: "@os20/engineering#conflictsWith",
        name: "conflictsWith",
        source: "@os20/assurance#RequirementDefinition",
        target: "@os20/assurance#RequirementDefinition",
        cardinality: "*",
        transitive: false,
        symmetric: true,
        inverse: None,
        authorship: RelationAuthorship::Authored,
        cycles: "n/a",
        v1: true,
        example: "MaxMassRequirement conflictsWith ArmorRequirement",
    },
    RelationDecl {
        id: "@os20/engineering#verifiedBy",
        name: "verifiedBy",
        source: "@os20/assurance#RequirementDefinition",
        target: "@os20/assurance#VerificationActivity",
        cardinality: "*",
        transitive: false,
        symmetric: false,
        inverse: None,
        authorship: RelationAuthorship::Authored,
        cycles: "n/a",
        v1: true,
        example: "TorqueRequirement verifiedBy DynoTestDef",
    },
    RelationDecl {
        id: "@os20/engineering#validatedBy",
        name: "validatedBy",
        source: "@os20/assurance#RequirementDefinition",
        target: "@os20/assurance#ValidationActivity",
        cardinality: "*",
        transitive: false,
        symmetric: false,
        inverse: None,
        authorship: RelationAuthorship::Authored,
        cycles: "n/a",
        v1: true,
        example: "ThermalRequirement validatedBy VehicleHeatSoak",
    },
    RelationDecl {
        id: "@os20/engineering#assertsSatisfaction",
        name: "assertsSatisfaction",
        source: "@os20/core#Thing",
        target: "@os20/assurance#RequirementDefinition",
        cardinality: "*",
        transitive: false,
        symmetric: false,
        inverse: None,
        authorship: RelationAuthorship::Authored,
        cycles: "n/a",
        v1: true,
        example: "intent only — not RequirementSatisfaction",
    },
    RelationDecl {
        id: "@os20/engineering#representedBy",
        name: "representedBy",
        source: "@os20/core#Thing",
        target: "@os20/lifecycle#ModelArtifact",
        cardinality: "*",
        transitive: false,
        symmetric: false,
        inverse: None,
        authorship: RelationAuthorship::Authored,
        cycles: "n/a",
        v1: true,
        example: "TractionMotorGeometry representedBy MotorStepArtifact",
    },
    RelationDecl {
        id: "@os20/engineering#describes",
        name: "describes",
        source: "@os20/lifecycle#ModelArtifact",
        target: "@os20/core#Thing",
        cardinality: "*",
        transitive: false,
        symmetric: false,
        inverse: None,
        authorship: RelationAuthorship::Authored,
        cycles: "n/a",
        v1: true,
        example: "SysmlSource describes TractionMotorDefinition",
    },
    RelationDecl {
        id: "@os20/engineering#derivedFrom",
        name: "derivedFrom",
        source: "@os20/core#Thing",
        target: "@os20/core#Thing",
        cardinality: "*",
        transitive: true,
        symmetric: false,
        inverse: None,
        authorship: RelationAuthorship::Authored,
        cycles: "forbidden",
        v1: true,
        example: "ThermalSimResult derivedFrom ThermalSimRun",
    },
    RelationDecl {
        id: "@os20/engineering#simulates",
        name: "simulates",
        source: "@os20/analysis#SimulationDefinition",
        target: "@os20/core#Thing",
        cardinality: "*",
        transitive: false,
        symmetric: false,
        inverse: Some("@os20/engineering#simulatedBy"),
        authorship: RelationAuthorship::Authored,
        cycles: "n/a",
        v1: true,
        example: "ThermalSimDef simulates TractionMotor",
    },
    RelationDecl {
        id: "@os20/engineering#simulatedBy",
        name: "simulatedBy",
        source: "@os20/core#Thing",
        target: "@os20/analysis#SimulationDefinition",
        cardinality: "*",
        transitive: false,
        symmetric: false,
        inverse: Some("@os20/engineering#simulates"),
        authorship: RelationAuthorship::Derived,
        cycles: "n/a",
        v1: true,
        example: "TractionMotor simulatedBy ThermalSimDef",
    },
    RelationDecl {
        id: "@os20/engineering#usesModel",
        name: "usesModel",
        source: "@os20/analysis#SimulationDefinition",
        target: "@os20/engineering#EngineeringModel",
        cardinality: "*",
        transitive: false,
        symmetric: false,
        inverse: None,
        authorship: RelationAuthorship::Authored,
        cycles: "n/a",
        v1: true,
        example: "ThermalSimDef usesModel MotorThermalModel",
    },
    RelationDecl {
        id: "@os20/engineering#usesGeometry",
        name: "usesGeometry",
        source: "@os20/analysis#SimulationDefinition",
        target: "@os20/physical#Geometry",
        cardinality: "*",
        transitive: false,
        symmetric: false,
        inverse: None,
        authorship: RelationAuthorship::Authored,
        cycles: "n/a",
        v1: true,
        example: "ThermalSimDef usesGeometry TractionMotorGeometry",
    },
    RelationDecl {
        id: "@os20/engineering#usesMaterial",
        name: "usesMaterial",
        source: "@os20/analysis#SimulationDefinition",
        target: "@os20/physical#MaterialDefinition",
        cardinality: "*",
        transitive: false,
        symmetric: false,
        inverse: None,
        authorship: RelationAuthorship::Authored,
        cycles: "n/a",
        v1: true,
        example: "ThermalSimDef usesMaterial Copper",
    },
    RelationDecl {
        id: "@os20/engineering#usesBoundaryCondition",
        name: "usesBoundaryCondition",
        source: "@os20/analysis#SimulationDefinition",
        target: "@os20/analysis#BoundaryCondition",
        cardinality: "*",
        transitive: false,
        symmetric: false,
        inverse: None,
        authorship: RelationAuthorship::Authored,
        cycles: "n/a",
        v1: true,
        example: "ThermalSimDef usesBoundaryCondition CoolantInletBc",
    },
    RelationDecl {
        id: "@os20/engineering#usesSolver",
        name: "usesSolver",
        source: "@os20/analysis#SimulationDefinition",
        target: "@os20/analysis#SolverReference",
        cardinality: "0..1",
        transitive: false,
        symmetric: false,
        inverse: None,
        authorship: RelationAuthorship::Authored,
        cycles: "n/a",
        v1: true,
        example: "ThermalSimDef usesSolver ConjugateHeatSolver",
    },
    RelationDecl {
        id: "@os20/engineering#producesResult",
        name: "producesResult",
        source: "@os20/engineering#EngineeringActivity",
        target: "@os20/engineering#EngineeringResult",
        cardinality: "*",
        transitive: false,
        symmetric: false,
        inverse: None,
        authorship: RelationAuthorship::Authored,
        cycles: "n/a",
        v1: true,
        example: "ThermalSimRun producesResult ThermalSimResult",
    },
    RelationDecl {
        id: "@os20/engineering#providesEvidenceFor",
        name: "providesEvidenceFor",
        source: "@os20/engineering#EngineeringEvidence",
        target: "@os20/assurance#RequirementDefinition",
        cardinality: "*",
        transitive: false,
        symmetric: false,
        inverse: None,
        authorship: RelationAuthorship::Authored,
        cycles: "n/a",
        v1: true,
        example: "DynoTestResult providesEvidenceFor TorqueRequirement",
    },
    RelationDecl {
        id: "@os20/engineering#manufacturedBy",
        name: "manufacturedBy",
        source: "@os20/engineering#PhysicalInstance",
        target: "@os20/lifecycle#ManufacturingPlan",
        cardinality: "0..1",
        transitive: false,
        symmetric: false,
        inverse: None,
        authorship: RelationAuthorship::Authored,
        cycles: "n/a",
        v1: true,
        example: "TractionMotor manufacturedBy MotorMfgPlan",
    },
    RelationDecl {
        id: "@os20/engineering#producedBy",
        name: "producedBy",
        source: "@os20/physical#GeometricFeature",
        target: "@os20/lifecycle#ManufacturingOperation",
        cardinality: "0..1",
        transitive: false,
        symmetric: false,
        inverse: None,
        authorship: RelationAuthorship::Authored,
        cycles: "n/a",
        v1: true,
        example: "CoolingHole producedBy DrillOp",
    },
    RelationDecl {
        id: "@os20/engineering#executesOn",
        name: "executesOn",
        source: "@os20/software#SoftwareComponent",
        target: "@os20/engineering#DeviceInstance",
        cardinality: "*",
        transitive: false,
        symmetric: false,
        inverse: None,
        authorship: RelationAuthorship::Authored,
        cycles: "n/a",
        v1: true,
        example: "MotorFirmware executesOn MotorController",
    },
    RelationDecl {
        id: "@os20/engineering#controls",
        name: "controls",
        source: "@os20/core#Thing",
        target: "@os20/core#Thing",
        cardinality: "*",
        transitive: false,
        symmetric: false,
        inverse: Some("@os20/engineering#controlledBy"),
        authorship: RelationAuthorship::Authored,
        cycles: "n/a",
        v1: true,
        example: "MotorController controls TractionMotor",
    },
    RelationDecl {
        id: "@os20/engineering#controlledBy",
        name: "controlledBy",
        source: "@os20/core#Thing",
        target: "@os20/core#Thing",
        cardinality: "*",
        transitive: false,
        symmetric: false,
        inverse: Some("@os20/engineering#controls"),
        authorship: RelationAuthorship::Derived,
        cycles: "n/a",
        v1: true,
        example: "TractionMotor controlledBy MotorController",
    },
    RelationDecl {
        id: "@os20/engineering#compatibleWith",
        name: "compatibleWith",
        source: "@os20/core#Thing",
        target: "@os20/core#Thing",
        cardinality: "*",
        transitive: false,
        symmetric: true,
        inverse: None,
        authorship: RelationAuthorship::Authored,
        cycles: "n/a",
        v1: true,
        example: "HVPort compatibleWith ControllerMotorPort",
    },
    RelationDecl {
        id: "@os20/engineering#incompatibleWith",
        name: "incompatibleWith",
        source: "@os20/engineering#Option",
        target: "@os20/engineering#Option",
        cardinality: "*",
        transitive: false,
        symmetric: true,
        inverse: None,
        authorship: RelationAuthorship::Authored,
        cycles: "n/a",
        v1: true,
        example: "AWDOption incompatibleWith TwoWheelBaseOption",
    },
    RelationDecl {
        id: "@os20/engineering#configures",
        name: "configures",
        source: "@os20/engineering#Configuration",
        target: "@os20/engineering#SystemInstance",
        cardinality: "1",
        transitive: false,
        symmetric: false,
        inverse: None,
        authorship: RelationAuthorship::Authored,
        cycles: "n/a",
        v1: true,
        example: "VehicleConfiguration configures EVPowertrain",
    },
    RelationDecl {
        id: "@os20/engineering#selects",
        name: "selects",
        source: "@os20/engineering#Configuration",
        target: "@os20/engineering#Option",
        cardinality: "*",
        transitive: false,
        symmetric: false,
        inverse: None,
        authorship: RelationAuthorship::Authored,
        cycles: "n/a",
        v1: true,
        example: "VehicleConfiguration selects PerformanceMotorOption",
    },
    RelationDecl {
        id: "@os20/engineering#excludes",
        name: "excludes",
        source: "@os20/engineering#Option",
        target: "@os20/engineering#Option",
        cardinality: "*",
        transitive: false,
        symmetric: true,
        inverse: None,
        authorship: RelationAuthorship::Authored,
        cycles: "n/a",
        v1: true,
        example: "PerformanceMotorOption excludes EconomyMotorOption",
    },
    RelationDecl {
        id: "@os20/engineering#generatedBy",
        name: "generatedBy",
        source: "@os20/engineering#EngineeringResult",
        target: "@os20/engineering#EngineeringActivity",
        cardinality: "1",
        transitive: false,
        symmetric: false,
        inverse: None,
        authorship: RelationAuthorship::Authored,
        cycles: "n/a",
        v1: true,
        example: "ThermalSimResult generatedBy ThermalSimRun",
    },
    RelationDecl {
        id: "@os20/engineering#providedBy",
        name: "providedBy",
        source: "@os20/engineering#EngineeringDefinition",
        target: "@os20/engineering#EngineeringThing",
        cardinality: "1",
        transitive: false,
        symmetric: false,
        inverse: None,
        authorship: RelationAuthorship::Authored,
        cycles: "n/a",
        v1: true,
        example: "maps to frozen PackageRelease, not a second package id",
    },
];
