//! Engineering ontology packages as bound SourceGraphs.

use std::collections::BTreeMap;

use crate::compiler::OntologyCompileRequest;
use crate::fixtures::{
    core_graph, core_manifest, electrical_graph, electrical_manifest, kerml_graph, kerml_manifest,
    physics_graph, physics_manifest,
};
use crate::identity::PackageId;
use crate::package::{PackageRole, SourceSpan, Visibility};
use crate::source_graph::{
    BoundElement, BoundFeature, BoundRelation, BoundSourceGraph, OntologyManifest,
};
use crate::source_tree::{FetchPolicy, OntologyResolveMode};
use crate::versions::OS20_ENGINEERING_ONTOLOGY_VERSION;

struct Row {
    name: &'static str,
    kind: &'static str,
    specs: &'static [&'static str],
    domains: &'static [&'static str],
    dim: Option<&'static str>,
}

fn el(
    name: &str,
    kind: &str,
    specs: &[&str],
    file: &str,
    domains: &[&str],
    features: Vec<BoundFeature>,
) -> BoundElement {
    BoundElement {
        qualified: None,
        name: name.into(),
        kind: kind.into(),
        visibility: Visibility::Public,
        specializes: specs.iter().map(|s| (*s).to_string()).collect(),
        mixins: vec![],
        features,
        domains: domains.iter().map(|s| (*s).to_string()).collect(),
        quantity_dimension: None,
        preferred_unit: None,
        value_type: None,
        replaced_by: None,
        split_into: vec![],
        lifecycle: crate::package::LifecycleStatus::Active,
        comment: None,
        inverse: None,
        transitive: false,
        symmetric: false,
        file: file.into(),
        span: SourceSpan { start: 0, end: 48 },
    }
}

fn qty(name: &str, dim: &str, file: &str) -> BoundElement {
    let mut e = el(
        name,
        "Quantity",
        &["@os20/core#Thing"],
        file,
        &["Physics"],
        vec![],
    );
    e.quantity_dimension = Some(dim.into());
    e.value_type = Some("@omg/kerml#Real".into());
    e
}

fn pred(
    name: &str,
    source: &str,
    target: &str,
    inverse: Option<&str>,
    transitive: bool,
    symmetric: bool,
    file: &str,
) -> BoundElement {
    let mut e = el(
        name,
        "Predicate",
        &[source],
        file,
        &["Design"],
        vec![BoundFeature {
            name: "target".into(),
            ty: target.into(),
            default_value: None,
        }],
    );
    e.inverse = inverse.map(str::to_string);
    e.transitive = transitive;
    e.symmetric = symmetric;
    e
}

fn graph(package: &str, file: &str, rows: &[Row], extra: Vec<BoundElement>) -> BoundSourceGraph {
    let mut elements: Vec<BoundElement> = rows
        .iter()
        .map(|r| {
            if let Some(dim) = r.dim {
                qty(r.name, dim, file)
            } else {
                el(r.name, r.kind, r.specs, file, r.domains, vec![])
            }
        })
        .collect();
    elements.extend(extra);
    BoundSourceGraph {
        package: package.into(),
        elements,
        relations: rows
            .iter()
            .flat_map(|r| {
                r.specs.iter().map(|s| BoundRelation {
                    kind: "Specialize".into(),
                    source: r.name.into(),
                    target: (*s).into(),
                })
            })
            .collect(),
        file_comments: vec![],
    }
}

fn manifest(name: PackageId, deps: Vec<PackageId>, root: &str) -> OntologyManifest {
    OntologyManifest {
        name,
        version: OS20_ENGINEERING_ONTOLOGY_VERSION.into(),
        role: PackageRole::Ontology,
        dependencies: deps,
        optional_dependencies: vec![],
        package_root: root.into(),
    }
}

/// All v1 engineering ontology packages (not including bootstrap core/physics).
pub fn engineering_packages() -> &'static [&'static str] {
    &[
        "@os20/engineering",
        "@os20/physical",
        "@os20/software",
        "@os20/assurance",
        "@os20/analysis",
        "@os20/lifecycle",
    ]
}

/// Manifests for a full engineering compile (includes frozen bootstrap packages).
pub fn engineering_manifests() -> Vec<OntologyManifest> {
    vec![
        kerml_manifest(),
        core_manifest(),
        physics_manifest(),
        electrical_manifest(),
        manifest(
            PackageId::os20_engineering(),
            vec![PackageId::os20_core(), PackageId::os20_physics()],
            "core/engineering",
        ),
        manifest(
            PackageId::os20_physical(),
            vec![
                PackageId::os20_engineering(),
                PackageId::os20_physics(),
                PackageId::os20_electrical(),
            ],
            "physical",
        ),
        manifest(
            PackageId::os20_software(),
            vec![PackageId::os20_engineering()],
            "behavior/software",
        ),
        manifest(
            PackageId::os20_assurance(),
            vec![PackageId::os20_engineering()],
            "assurance",
        ),
        manifest(
            PackageId::os20_analysis(),
            vec![PackageId::os20_engineering(), PackageId::os20_physical()],
            "analysis",
        ),
        manifest(
            PackageId::os20_lifecycle(),
            vec![PackageId::os20_engineering(), PackageId::os20_physical()],
            "lifecycle",
        ),
    ]
}

/// Bound graphs keyed by package id.
pub fn engineering_graphs() -> BTreeMap<String, BoundSourceGraph> {
    BTreeMap::from([
        ("@omg/kerml".into(), kerml_graph()),
        ("@os20/core".into(), core_graph()),
        ("@os20/physics".into(), physics_graph()),
        ("@os20/electrical".into(), electrical_graph()),
        ("@os20/engineering".into(), engineering_graph()),
        ("@os20/physical".into(), physical_graph()),
        ("@os20/software".into(), software_graph()),
        ("@os20/assurance".into(), assurance_graph()),
        ("@os20/analysis".into(), analysis_graph()),
        ("@os20/lifecycle".into(), lifecycle_graph()),
    ])
}

/// Locked-offline compile request for the v1 engineering ontology.
pub fn engineering_compile_request() -> OntologyCompileRequest {
    OntologyCompileRequest {
        mode: OntologyResolveMode::LockedOffline,
        fetch: FetchPolicy::Never,
        manifests: engineering_manifests(),
        graphs: engineering_graphs(),
        ..OntologyCompileRequest::default()
    }
}

fn engineering_graph() -> BoundSourceGraph {
    let rows = [
        Row {
            name: "EngineeringThing",
            kind: "Classifier",
            specs: &["@os20/core#Thing"],
            domains: &["Design"],
            dim: None,
        },
        Row {
            name: "EngineeringDefinition",
            kind: "Classifier",
            specs: &["EngineeringThing"],
            domains: &["Design"],
            dim: None,
        },
        Row {
            name: "EngineeringInstance",
            kind: "Classifier",
            specs: &["EngineeringThing"],
            domains: &["Design"],
            dim: None,
        },
        Row {
            name: "EngineeringProperty",
            kind: "Classifier",
            specs: &["EngineeringThing"],
            domains: &["Design"],
            dim: None,
        },
        Row {
            name: "QuantityProperty",
            kind: "Classifier",
            specs: &["EngineeringProperty"],
            domains: &["Physics"],
            dim: None,
        },
        Row {
            name: "BooleanProperty",
            kind: "Classifier",
            specs: &["EngineeringProperty"],
            domains: &["Design"],
            dim: None,
        },
        Row {
            name: "EnumeratedProperty",
            kind: "Classifier",
            specs: &["EngineeringProperty"],
            domains: &["Design"],
            dim: None,
        },
        Row {
            name: "TextProperty",
            kind: "Classifier",
            specs: &["EngineeringProperty"],
            domains: &["Design"],
            dim: None,
        },
        Row {
            name: "ReferenceProperty",
            kind: "Classifier",
            specs: &["EngineeringProperty"],
            domains: &["Design"],
            dim: None,
        },
        Row {
            name: "EngineeringModel",
            kind: "Classifier",
            specs: &["EngineeringDefinition"],
            domains: &["Design"],
            dim: None,
        },
        Row {
            name: "EngineeringActivity",
            kind: "Classifier",
            specs: &["EngineeringDefinition"],
            domains: &["Behaviour"],
            dim: None,
        },
        Row {
            name: "EngineeringResult",
            kind: "Classifier",
            specs: &["EngineeringThing"],
            domains: &["Verification"],
            dim: None,
        },
        Row {
            name: "EngineeringEvidence",
            kind: "Classifier",
            specs: &["EngineeringThing"],
            domains: &["Verification"],
            dim: None,
        },
        Row {
            name: "EngineeringDocument",
            kind: "Classifier",
            specs: &["EngineeringThing"],
            domains: &["Design"],
            dim: None,
        },
        Row {
            name: "SystemDefinition",
            kind: "Classifier",
            specs: &["EngineeringDefinition"],
            domains: &["Structure"],
            dim: None,
        },
        Row {
            name: "SystemInstance",
            kind: "Classifier",
            specs: &["EngineeringInstance"],
            domains: &["Structure"],
            dim: None,
        },
        Row {
            name: "PhysicalDefinition",
            kind: "Classifier",
            specs: &["EngineeringDefinition", "@os20/core#PhysicalThing"],
            domains: &["Structure", "Physics"],
            dim: None,
        },
        Row {
            name: "PhysicalInstance",
            kind: "Classifier",
            specs: &["EngineeringInstance", "@os20/core#PhysicalThing"],
            domains: &["Structure", "Physics"],
            dim: None,
        },
        Row {
            name: "AssemblyDefinition",
            kind: "Classifier",
            specs: &["PhysicalDefinition"],
            domains: &["Structure"],
            dim: None,
        },
        Row {
            name: "AssemblyInstance",
            kind: "Classifier",
            specs: &["PhysicalInstance"],
            domains: &["Structure"],
            dim: None,
        },
        Row {
            name: "PartDefinition",
            kind: "Classifier",
            specs: &["PhysicalDefinition"],
            domains: &["Structure"],
            dim: None,
        },
        Row {
            name: "PartInstance",
            kind: "Classifier",
            specs: &["PhysicalInstance"],
            domains: &["Structure"],
            dim: None,
        },
        Row {
            name: "DeviceDefinition",
            kind: "Classifier",
            specs: &["PhysicalDefinition"],
            domains: &["Structure"],
            dim: None,
        },
        Row {
            name: "DeviceInstance",
            kind: "Classifier",
            specs: &["PhysicalInstance"],
            domains: &["Structure"],
            dim: None,
        },
        Row {
            name: "BehaviorDefinition",
            kind: "Classifier",
            specs: &["EngineeringDefinition", "@os20/core#BehaviouralThing"],
            domains: &["Behaviour"],
            dim: None,
        },
        Row {
            name: "BehaviorInstance",
            kind: "Classifier",
            specs: &["EngineeringInstance"],
            domains: &["Behaviour"],
            dim: None,
        },
        Row {
            name: "StateMachine",
            kind: "Classifier",
            specs: &["BehaviorDefinition"],
            domains: &["Behaviour"],
            dim: None,
        },
        Row {
            name: "State",
            kind: "Classifier",
            specs: &["EngineeringThing"],
            domains: &["Behaviour"],
            dim: None,
        },
        Row {
            name: "Transition",
            kind: "Classifier",
            specs: &["EngineeringThing"],
            domains: &["Behaviour"],
            dim: None,
        },
        Row {
            name: "Event",
            kind: "Classifier",
            specs: &["EngineeringThing"],
            domains: &["Behaviour"],
            dim: None,
        },
        Row {
            name: "Function",
            kind: "Classifier",
            specs: &["BehaviorDefinition"],
            domains: &["Behaviour"],
            dim: None,
        },
        Row {
            name: "Mode",
            kind: "Classifier",
            specs: &["EngineeringThing"],
            domains: &["Behaviour"],
            dim: None,
        },
        Row {
            name: "InterfaceDefinition",
            kind: "Classifier",
            specs: &["EngineeringDefinition"],
            domains: &["Structure"],
            dim: None,
        },
        Row {
            name: "PortDefinition",
            kind: "Classifier",
            specs: &["EngineeringDefinition"],
            domains: &["Structure"],
            dim: None,
        },
        Row {
            name: "PortInstance",
            kind: "Classifier",
            specs: &["EngineeringInstance"],
            domains: &["Structure"],
            dim: None,
        },
        Row {
            name: "ConnectionDefinition",
            kind: "Classifier",
            specs: &["EngineeringDefinition"],
            domains: &["Structure"],
            dim: None,
        },
        Row {
            name: "ConnectionInstance",
            kind: "Classifier",
            specs: &["EngineeringInstance"],
            domains: &["Structure"],
            dim: None,
        },
        Row {
            name: "MechanicalPort",
            kind: "Classifier",
            specs: &["PortDefinition"],
            domains: &["Structure"],
            dim: None,
        },
        Row {
            name: "ElectricalPort",
            kind: "Classifier",
            specs: &["PortDefinition"],
            domains: &["Electrical"],
            dim: None,
        },
        Row {
            name: "FluidPort",
            kind: "Classifier",
            specs: &["PortDefinition"],
            domains: &["Physics"],
            dim: None,
        },
        Row {
            name: "ThermalPort",
            kind: "Classifier",
            specs: &["PortDefinition"],
            domains: &["Physics"],
            dim: None,
        },
        Row {
            name: "DataPort",
            kind: "Classifier",
            specs: &["PortDefinition"],
            domains: &["Behaviour"],
            dim: None,
        },
        Row {
            name: "EnergyFlow",
            kind: "Classifier",
            specs: &["EngineeringThing"],
            domains: &["Physics"],
            dim: None,
        },
        Row {
            name: "MaterialFlow",
            kind: "Classifier",
            specs: &["EngineeringThing"],
            domains: &["Physics"],
            dim: None,
        },
        Row {
            name: "InformationFlow",
            kind: "Classifier",
            specs: &["EngineeringThing"],
            domains: &["Behaviour"],
            dim: None,
        },
        Row {
            name: "Signal",
            kind: "Classifier",
            specs: &["InformationFlow"],
            domains: &["Behaviour"],
            dim: None,
        },
        Row {
            name: "Channel",
            kind: "Classifier",
            specs: &["EngineeringThing"],
            domains: &["Behaviour"],
            dim: None,
        },
        Row {
            name: "ConfigurationDefinition",
            kind: "Classifier",
            specs: &["EngineeringDefinition"],
            domains: &["Design"],
            dim: None,
        },
        Row {
            name: "Configuration",
            kind: "Classifier",
            specs: &["EngineeringInstance"],
            domains: &["Design"],
            dim: None,
        },
        Row {
            name: "Variant",
            kind: "Classifier",
            specs: &["Configuration"],
            domains: &["Design"],
            dim: None,
        },
        Row {
            name: "Option",
            kind: "Classifier",
            specs: &["EngineeringThing"],
            domains: &["Design"],
            dim: None,
        },
    ];
    let extra = vec![
        pred(
            "instanceOf",
            "EngineeringInstance",
            "EngineeringDefinition",
            Some("instantiates"),
            false,
            false,
            "Relations.sysml",
        ),
        pred(
            "instantiates",
            "EngineeringDefinition",
            "EngineeringInstance",
            Some("instanceOf"),
            false,
            false,
            "Relations.sysml",
        ),
        pred(
            "partOf",
            "@os20/core#Thing",
            "@os20/core#Thing",
            Some("@os20/core#contains"),
            true,
            false,
            "Relations.sysml",
        ),
        pred(
            "hasProperty",
            "@os20/core#Thing",
            "EngineeringProperty",
            None,
            false,
            false,
            "Relations.sysml",
        ),
        pred(
            "hasGeometry",
            "PhysicalInstance",
            "EngineeringModel",
            None,
            false,
            false,
            "Relations.sysml",
        ),
        pred(
            "hasBehavior",
            "@os20/core#Thing",
            "BehaviorDefinition",
            None,
            false,
            false,
            "Relations.sysml",
        ),
        pred(
            "madeOf",
            "PhysicalInstance",
            "EngineeringDefinition",
            None,
            false,
            false,
            "Relations.sysml",
        ),
        pred(
            "hasMaterialAssignment",
            "PhysicalInstance",
            "EngineeringThing",
            None,
            false,
            false,
            "Relations.sysml",
        ),
        pred(
            "appliesToRegion",
            "EngineeringThing",
            "EngineeringThing",
            None,
            false,
            false,
            "Relations.sysml",
        ),
        pred(
            "hasPort",
            "@os20/core#Thing",
            "PortInstance",
            None,
            false,
            false,
            "Relations.sysml",
        ),
        pred(
            "connects",
            "ConnectionInstance",
            "PortInstance",
            Some("connectedTo"),
            false,
            false,
            "Relations.sysml",
        ),
        pred(
            "connectedTo",
            "PortInstance",
            "PortInstance",
            None,
            false,
            true,
            "Relations.sysml",
        ),
        pred(
            "realizes",
            "@os20/core#Thing",
            "EngineeringDefinition",
            None,
            false,
            false,
            "Relations.sysml",
        ),
        pred(
            "implements",
            "EngineeringDefinition",
            "InterfaceDefinition",
            None,
            false,
            false,
            "Relations.sysml",
        ),
        pred(
            "requires",
            "@os20/core#Thing",
            "@os20/core#Thing",
            None,
            false,
            false,
            "Relations.sysml",
        ),
        pred(
            "allocatedTo",
            "EngineeringDefinition",
            "@os20/core#Thing",
            Some("hasAllocatedRequirement"),
            false,
            false,
            "Relations.sysml",
        ),
        pred(
            "hasAllocatedRequirement",
            "@os20/core#Thing",
            "EngineeringDefinition",
            Some("allocatedTo"),
            false,
            false,
            "Relations.sysml",
        ),
        pred(
            "refines",
            "EngineeringDefinition",
            "EngineeringDefinition",
            None,
            true,
            false,
            "Relations.sysml",
        ),
        pred(
            "conflictsWith",
            "EngineeringDefinition",
            "EngineeringDefinition",
            None,
            false,
            true,
            "Relations.sysml",
        ),
        pred(
            "verifiedBy",
            "EngineeringDefinition",
            "EngineeringActivity",
            None,
            false,
            false,
            "Relations.sysml",
        ),
        pred(
            "validatedBy",
            "EngineeringDefinition",
            "EngineeringActivity",
            None,
            false,
            false,
            "Relations.sysml",
        ),
        pred(
            "assertsSatisfaction",
            "@os20/core#Thing",
            "EngineeringDefinition",
            None,
            false,
            false,
            "Relations.sysml",
        ),
        pred(
            "representedBy",
            "@os20/core#Thing",
            "EngineeringThing",
            None,
            false,
            false,
            "Relations.sysml",
        ),
        pred(
            "describes",
            "EngineeringThing",
            "@os20/core#Thing",
            None,
            false,
            false,
            "Relations.sysml",
        ),
        pred(
            "derivedFrom",
            "@os20/core#Thing",
            "@os20/core#Thing",
            None,
            true,
            false,
            "Relations.sysml",
        ),
        pred(
            "simulates",
            "EngineeringActivity",
            "@os20/core#Thing",
            Some("simulatedBy"),
            false,
            false,
            "Relations.sysml",
        ),
        pred(
            "simulatedBy",
            "@os20/core#Thing",
            "EngineeringActivity",
            Some("simulates"),
            false,
            false,
            "Relations.sysml",
        ),
        pred(
            "usesModel",
            "EngineeringActivity",
            "EngineeringModel",
            None,
            false,
            false,
            "Relations.sysml",
        ),
        pred(
            "usesGeometry",
            "EngineeringActivity",
            "EngineeringModel",
            None,
            false,
            false,
            "Relations.sysml",
        ),
        pred(
            "usesMaterial",
            "EngineeringActivity",
            "EngineeringDefinition",
            None,
            false,
            false,
            "Relations.sysml",
        ),
        pred(
            "usesBoundaryCondition",
            "EngineeringActivity",
            "EngineeringThing",
            None,
            false,
            false,
            "Relations.sysml",
        ),
        pred(
            "usesSolver",
            "EngineeringActivity",
            "EngineeringThing",
            None,
            false,
            false,
            "Relations.sysml",
        ),
        pred(
            "producesResult",
            "EngineeringThing",
            "EngineeringResult",
            None,
            false,
            false,
            "Relations.sysml",
        ),
        pred(
            "providesEvidenceFor",
            "EngineeringEvidence",
            "EngineeringDefinition",
            None,
            false,
            false,
            "Relations.sysml",
        ),
        pred(
            "manufacturedBy",
            "PhysicalInstance",
            "EngineeringDefinition",
            None,
            false,
            false,
            "Relations.sysml",
        ),
        pred(
            "producedBy",
            "EngineeringThing",
            "EngineeringActivity",
            None,
            false,
            false,
            "Relations.sysml",
        ),
        pred(
            "executesOn",
            "EngineeringDefinition",
            "DeviceInstance",
            None,
            false,
            false,
            "Relations.sysml",
        ),
        pred(
            "controls",
            "@os20/core#Thing",
            "@os20/core#Thing",
            Some("controlledBy"),
            false,
            false,
            "Relations.sysml",
        ),
        pred(
            "controlledBy",
            "@os20/core#Thing",
            "@os20/core#Thing",
            Some("controls"),
            false,
            false,
            "Relations.sysml",
        ),
        pred(
            "compatibleWith",
            "@os20/core#Thing",
            "@os20/core#Thing",
            None,
            false,
            true,
            "Relations.sysml",
        ),
        pred(
            "incompatibleWith",
            "Option",
            "Option",
            None,
            false,
            true,
            "Relations.sysml",
        ),
        pred(
            "configures",
            "Configuration",
            "SystemInstance",
            None,
            false,
            false,
            "Relations.sysml",
        ),
        pred(
            "selects",
            "Configuration",
            "Option",
            None,
            false,
            false,
            "Relations.sysml",
        ),
        pred(
            "excludes",
            "Option",
            "Option",
            None,
            false,
            true,
            "Relations.sysml",
        ),
        pred(
            "generatedBy",
            "EngineeringResult",
            "EngineeringActivity",
            None,
            false,
            false,
            "Relations.sysml",
        ),
        pred(
            "providedBy",
            "EngineeringDefinition",
            "EngineeringThing",
            None,
            false,
            false,
            "Relations.sysml",
        ),
    ];
    graph("@os20/engineering", "Engineering.sysml", &rows, extra)
}

fn physical_graph() -> BoundSourceGraph {
    let rows = [
        Row {
            name: "Geometry",
            kind: "Classifier",
            specs: &["@os20/engineering#EngineeringModel"],
            domains: &["Geometry"],
            dim: None,
        },
        Row {
            name: "GeometryModel",
            kind: "Classifier",
            specs: &["Geometry"],
            domains: &["Geometry"],
            dim: None,
        },
        Row {
            name: "GeometricRepresentation",
            kind: "Classifier",
            specs: &["@os20/engineering#EngineeringThing"],
            domains: &["Geometry"],
            dim: None,
        },
        Row {
            name: "SolidGeometry",
            kind: "Classifier",
            specs: &["Geometry"],
            domains: &["Geometry"],
            dim: None,
        },
        Row {
            name: "SurfaceGeometry",
            kind: "Classifier",
            specs: &["Geometry"],
            domains: &["Geometry"],
            dim: None,
        },
        Row {
            name: "WireGeometry",
            kind: "Classifier",
            specs: &["Geometry"],
            domains: &["Geometry"],
            dim: None,
        },
        Row {
            name: "MeshGeometry",
            kind: "Classifier",
            specs: &["Geometry"],
            domains: &["Geometry"],
            dim: None,
        },
        Row {
            name: "CADModel",
            kind: "Classifier",
            specs: &["GeometryModel"],
            domains: &["Geometry"],
            dim: None,
        },
        Row {
            name: "GeometricEntity",
            kind: "Classifier",
            specs: &["@os20/engineering#EngineeringThing"],
            domains: &["Geometry"],
            dim: None,
        },
        Row {
            name: "GeometricFeature",
            kind: "Classifier",
            specs: &["GeometricEntity"],
            domains: &["Geometry"],
            dim: None,
        },
        Row {
            name: "HoleFeature",
            kind: "Classifier",
            specs: &["GeometricFeature"],
            domains: &["Geometry"],
            dim: None,
        },
        Row {
            name: "SlotFeature",
            kind: "Classifier",
            specs: &["GeometricFeature"],
            domains: &["Geometry"],
            dim: None,
        },
        Row {
            name: "PocketFeature",
            kind: "Classifier",
            specs: &["GeometricFeature"],
            domains: &["Geometry"],
            dim: None,
        },
        Row {
            name: "FilletFeature",
            kind: "Classifier",
            specs: &["GeometricFeature"],
            domains: &["Geometry"],
            dim: None,
        },
        Row {
            name: "ChamferFeature",
            kind: "Classifier",
            specs: &["GeometricFeature"],
            domains: &["Geometry"],
            dim: None,
        },
        Row {
            name: "ReferenceFrame",
            kind: "Classifier",
            specs: &["GeometricEntity"],
            domains: &["Geometry"],
            dim: None,
        },
        Row {
            name: "Datum",
            kind: "Classifier",
            specs: &["GeometricEntity"],
            domains: &["Geometry"],
            dim: None,
        },
        Row {
            name: "BoundingBox",
            kind: "Structure",
            specs: &["@os20/engineering#EngineeringThing"],
            domains: &["Geometry"],
            dim: None,
        },
        Row {
            name: "MaterialDefinition",
            kind: "Classifier",
            specs: &["@os20/engineering#EngineeringDefinition"],
            domains: &["Physics"],
            dim: None,
        },
        Row {
            name: "Metal",
            kind: "Classifier",
            specs: &["MaterialDefinition"],
            domains: &["Physics"],
            dim: None,
        },
        Row {
            name: "Polymer",
            kind: "Classifier",
            specs: &["MaterialDefinition"],
            domains: &["Physics"],
            dim: None,
        },
        Row {
            name: "Composite",
            kind: "Classifier",
            specs: &["MaterialDefinition"],
            domains: &["Physics"],
            dim: None,
        },
        Row {
            name: "Ceramic",
            kind: "Classifier",
            specs: &["MaterialDefinition"],
            domains: &["Physics"],
            dim: None,
        },
        Row {
            name: "Fluid",
            kind: "Classifier",
            specs: &["MaterialDefinition"],
            domains: &["Physics"],
            dim: None,
        },
        Row {
            name: "Semiconductor",
            kind: "Classifier",
            specs: &["MaterialDefinition"],
            domains: &["Physics"],
            dim: None,
        },
        Row {
            name: "MaterialAssignment",
            kind: "Classifier",
            specs: &["@os20/engineering#EngineeringThing"],
            domains: &["Physics"],
            dim: None,
        },
        Row {
            name: "ElectricalComponent",
            kind: "Classifier",
            specs: &["@os20/engineering#DeviceDefinition"],
            domains: &["Electrical"],
            dim: None,
        },
        Row {
            name: "Circuit",
            kind: "Classifier",
            specs: &["@os20/engineering#EngineeringDefinition"],
            domains: &["Electrical"],
            dim: None,
        },
        Row {
            name: "PCB",
            kind: "Classifier",
            specs: &["@os20/engineering#PartDefinition"],
            domains: &["Electrical"],
            dim: None,
        },
        Row {
            name: "Sensor",
            kind: "Classifier",
            specs: &["@os20/engineering#DeviceDefinition"],
            domains: &["Electrical"],
            dim: None,
        },
        Row {
            name: "Actuator",
            kind: "Classifier",
            specs: &["@os20/engineering#DeviceDefinition"],
            domains: &["Electrical"],
            dim: None,
        },
        Row {
            name: "Battery",
            kind: "Classifier",
            specs: &["@os20/engineering#DeviceDefinition"],
            domains: &["Electrical"],
            dim: None,
        },
        Row {
            name: "PowerSupply",
            kind: "Classifier",
            specs: &["@os20/engineering#DeviceDefinition"],
            domains: &["Electrical"],
            dim: None,
        },
        Row {
            name: "ElectricalConnector",
            kind: "Classifier",
            specs: &["@os20/engineering#DeviceDefinition"],
            domains: &["Electrical"],
            dim: None,
        },
        Row {
            name: "Harness",
            kind: "Classifier",
            specs: &["@os20/engineering#AssemblyDefinition"],
            domains: &["Electrical"],
            dim: None,
        },
        Row {
            name: "TractionMotorDefinition",
            kind: "Classifier",
            specs: &[
                "@os20/engineering#DeviceDefinition",
                "@os20/electrical#ElectricMotor",
            ],
            domains: &["Electrical", "Structure", "Behaviour"],
            dim: None,
        },
        Row {
            name: "ThermalModel",
            kind: "Classifier",
            specs: &["@os20/engineering#EngineeringModel"],
            domains: &["Physics"],
            dim: None,
        },
        Row {
            name: "HeatSource",
            kind: "Classifier",
            specs: &["@os20/engineering#EngineeringThing"],
            domains: &["Physics"],
            dim: None,
        },
        Row {
            name: "HeatSink",
            kind: "Classifier",
            specs: &["@os20/engineering#EngineeringThing"],
            domains: &["Physics"],
            dim: None,
        },
        Row {
            name: "ThermalInterface",
            kind: "Classifier",
            specs: &["@os20/engineering#InterfaceDefinition"],
            domains: &["Physics"],
            dim: None,
        },
        Row {
            name: "ThermalBoundaryCondition",
            kind: "Classifier",
            specs: &["@os20/engineering#EngineeringThing"],
            domains: &["Physics"],
            dim: None,
        },
        Row {
            name: "Force",
            kind: "Quantity",
            specs: &["@os20/core#Thing"],
            domains: &["Physics"],
            dim: Some("M L T^-2"),
        },
        Row {
            name: "Torque",
            kind: "Quantity",
            specs: &["@os20/core#Thing"],
            domains: &["Physics"],
            dim: Some("M L^2 T^-2"),
        },
        Row {
            name: "Velocity",
            kind: "Quantity",
            specs: &["@os20/core#Thing"],
            domains: &["Physics"],
            dim: Some("L T^-1"),
        },
        Row {
            name: "Pressure",
            kind: "Quantity",
            specs: &["@os20/core#Thing"],
            domains: &["Physics"],
            dim: Some("M L^-1 T^-2"),
        },
        Row {
            name: "Angle",
            kind: "Quantity",
            specs: &["@os20/core#Thing"],
            domains: &["Physics"],
            dim: Some("1"),
        },
    ];
    graph("@os20/physical", "Physical.sysml", &rows, vec![])
}

fn software_graph() -> BoundSourceGraph {
    let rows = [
        Row {
            name: "SoftwareComponent",
            kind: "Classifier",
            specs: &["@os20/engineering#EngineeringDefinition"],
            domains: &["Behaviour"],
            dim: None,
        },
        Row {
            name: "EmbeddedSoftware",
            kind: "Classifier",
            specs: &["SoftwareComponent"],
            domains: &["Behaviour"],
            dim: None,
        },
        Row {
            name: "Firmware",
            kind: "Classifier",
            specs: &["SoftwareComponent"],
            domains: &["Behaviour"],
            dim: None,
        },
        Row {
            name: "API",
            kind: "Classifier",
            specs: &["@os20/engineering#InterfaceDefinition"],
            domains: &["Behaviour"],
            dim: None,
        },
        Row {
            name: "Protocol",
            kind: "Classifier",
            specs: &["@os20/engineering#EngineeringDefinition"],
            domains: &["Behaviour"],
            dim: None,
        },
        Row {
            name: "Message",
            kind: "Classifier",
            specs: &["@os20/engineering#EngineeringThing"],
            domains: &["Behaviour"],
            dim: None,
        },
    ];
    graph("@os20/software", "Software.sysml", &rows, vec![])
}

fn assurance_graph() -> BoundSourceGraph {
    let rows = [
        Row {
            name: "RequirementDefinition",
            kind: "Classifier",
            specs: &["@os20/engineering#EngineeringDefinition"],
            domains: &["Requirements"],
            dim: None,
        },
        Row {
            name: "FunctionalRequirement",
            kind: "Classifier",
            specs: &["RequirementDefinition"],
            domains: &["Requirements"],
            dim: None,
        },
        Row {
            name: "PerformanceRequirement",
            kind: "Classifier",
            specs: &["RequirementDefinition"],
            domains: &["Requirements"],
            dim: None,
        },
        Row {
            name: "SafetyRequirement",
            kind: "Classifier",
            specs: &["RequirementDefinition"],
            domains: &["Safety"],
            dim: None,
        },
        Row {
            name: "InterfaceRequirement",
            kind: "Classifier",
            specs: &["RequirementDefinition"],
            domains: &["Requirements"],
            dim: None,
        },
        Row {
            name: "EnvironmentalRequirement",
            kind: "Classifier",
            specs: &["RequirementDefinition"],
            domains: &["Requirements"],
            dim: None,
        },
        Row {
            name: "RegulatoryRequirement",
            kind: "Classifier",
            specs: &["RequirementDefinition"],
            domains: &["Compliance"],
            dim: None,
        },
        Row {
            name: "ConstraintRequirement",
            kind: "Classifier",
            specs: &["RequirementDefinition"],
            domains: &["Requirements"],
            dim: None,
        },
        Row {
            name: "ConstraintPurpose",
            kind: "Classifier",
            specs: &["@os20/engineering#EngineeringThing"],
            domains: &["Requirements"],
            dim: None,
        },
        Row {
            name: "RangeConstraint",
            kind: "Classifier",
            specs: &["ConstraintPurpose"],
            domains: &["Requirements"],
            dim: None,
        },
        Row {
            name: "CompatibilityConstraint",
            kind: "Classifier",
            specs: &["ConstraintPurpose"],
            domains: &["Requirements"],
            dim: None,
        },
        Row {
            name: "FitConstraint",
            kind: "Classifier",
            specs: &["ConstraintPurpose"],
            domains: &["Requirements"],
            dim: None,
        },
        Row {
            name: "VerificationActivity",
            kind: "Classifier",
            specs: &["@os20/engineering#EngineeringActivity"],
            domains: &["Verification"],
            dim: None,
        },
        Row {
            name: "ValidationActivity",
            kind: "Classifier",
            specs: &["@os20/engineering#EngineeringActivity"],
            domains: &["Validation"],
            dim: None,
        },
        Row {
            name: "TestDefinition",
            kind: "Classifier",
            specs: &["VerificationActivity"],
            domains: &["Verification"],
            dim: None,
        },
        Row {
            name: "TestExecution",
            kind: "Classifier",
            specs: &["@os20/engineering#EngineeringInstance"],
            domains: &["Verification"],
            dim: None,
        },
        Row {
            name: "TestResult",
            kind: "Classifier",
            specs: &[
                "@os20/engineering#EngineeringResult",
                "@os20/engineering#EngineeringEvidence",
            ],
            domains: &["Verification"],
            dim: None,
        },
        Row {
            name: "InspectionActivity",
            kind: "Classifier",
            specs: &["VerificationActivity"],
            domains: &["Verification"],
            dim: None,
        },
        Row {
            name: "ReviewActivity",
            kind: "Classifier",
            specs: &["VerificationActivity"],
            domains: &["Verification"],
            dim: None,
        },
        Row {
            name: "FailureMode",
            kind: "Classifier",
            specs: &["@os20/engineering#EngineeringThing"],
            domains: &["Safety"],
            dim: None,
        },
        Row {
            name: "Hazard",
            kind: "Classifier",
            specs: &["@os20/engineering#EngineeringThing"],
            domains: &["Safety"],
            dim: None,
        },
        Row {
            name: "Risk",
            kind: "Classifier",
            specs: &["@os20/engineering#EngineeringThing"],
            domains: &["Safety"],
            dim: None,
        },
        Row {
            name: "Mitigation",
            kind: "Classifier",
            specs: &["@os20/engineering#EngineeringThing"],
            domains: &["Safety"],
            dim: None,
        },
    ];
    graph("@os20/assurance", "Assurance.sysml", &rows, vec![])
}

fn analysis_graph() -> BoundSourceGraph {
    let rows = [
        Row {
            name: "SimulationDefinition",
            kind: "Classifier",
            specs: &["@os20/engineering#EngineeringActivity"],
            domains: &["Simulation"],
            dim: None,
        },
        Row {
            name: "SimulationModel",
            kind: "Classifier",
            specs: &["@os20/engineering#EngineeringModel"],
            domains: &["Simulation"],
            dim: None,
        },
        Row {
            name: "SimulationScenario",
            kind: "Classifier",
            specs: &["@os20/engineering#EngineeringThing"],
            domains: &["Simulation"],
            dim: None,
        },
        Row {
            name: "SimulationRun",
            kind: "Classifier",
            specs: &["@os20/engineering#EngineeringInstance"],
            domains: &["Simulation"],
            dim: None,
        },
        Row {
            name: "SimulationResult",
            kind: "Classifier",
            specs: &[
                "@os20/engineering#EngineeringResult",
                "@os20/engineering#EngineeringEvidence",
            ],
            domains: &["Simulation"],
            dim: None,
        },
        Row {
            name: "SolverReference",
            kind: "Classifier",
            specs: &["@os20/engineering#EngineeringThing"],
            domains: &["Simulation"],
            dim: None,
        },
        Row {
            name: "SimulationEnvironment",
            kind: "Classifier",
            specs: &["@os20/engineering#EngineeringThing"],
            domains: &["Simulation"],
            dim: None,
        },
        Row {
            name: "BoundaryCondition",
            kind: "Classifier",
            specs: &["@os20/engineering#EngineeringThing"],
            domains: &["Simulation"],
            dim: None,
        },
        Row {
            name: "InitialCondition",
            kind: "Classifier",
            specs: &["@os20/engineering#EngineeringThing"],
            domains: &["Simulation"],
            dim: None,
        },
        Row {
            name: "StructuralSimulation",
            kind: "Classifier",
            specs: &["SimulationDefinition"],
            domains: &["Simulation"],
            dim: None,
        },
        Row {
            name: "ThermalSimulation",
            kind: "Classifier",
            specs: &["SimulationDefinition"],
            domains: &["Simulation"],
            dim: None,
        },
        Row {
            name: "SystemSimulation",
            kind: "Classifier",
            specs: &["SimulationDefinition"],
            domains: &["Simulation"],
            dim: None,
        },
        Row {
            name: "Analysis",
            kind: "Classifier",
            specs: &["@os20/engineering#EngineeringActivity"],
            domains: &["Simulation"],
            dim: None,
        },
        Row {
            name: "AnalysisResult",
            kind: "Classifier",
            specs: &["@os20/engineering#EngineeringResult"],
            domains: &["Simulation"],
            dim: None,
        },
    ];
    graph("@os20/analysis", "Analysis.sysml", &rows, vec![])
}

fn lifecycle_graph() -> BoundSourceGraph {
    let rows = [
        Row {
            name: "ManufacturingPlan",
            kind: "Classifier",
            specs: &["@os20/engineering#EngineeringDefinition"],
            domains: &["Manufacturing"],
            dim: None,
        },
        Row {
            name: "ManufacturingProcess",
            kind: "Classifier",
            specs: &["@os20/engineering#EngineeringActivity"],
            domains: &["Manufacturing"],
            dim: None,
        },
        Row {
            name: "ManufacturingOperation",
            kind: "Classifier",
            specs: &["@os20/engineering#EngineeringActivity"],
            domains: &["Manufacturing"],
            dim: None,
        },
        Row {
            name: "ManufacturingMachine",
            kind: "Classifier",
            specs: &["@os20/engineering#DeviceDefinition"],
            domains: &["Manufacturing"],
            dim: None,
        },
        Row {
            name: "ManufacturingTool",
            kind: "Classifier",
            specs: &["@os20/engineering#EngineeringThing"],
            domains: &["Manufacturing"],
            dim: None,
        },
        Row {
            name: "Fixture",
            kind: "Classifier",
            specs: &["@os20/engineering#PartDefinition"],
            domains: &["Manufacturing"],
            dim: None,
        },
        Row {
            name: "ProcessParameter",
            kind: "Classifier",
            specs: &["@os20/engineering#EngineeringProperty"],
            domains: &["Manufacturing"],
            dim: None,
        },
        Row {
            name: "Machining",
            kind: "Classifier",
            specs: &["ManufacturingProcess"],
            domains: &["Manufacturing"],
            dim: None,
        },
        Row {
            name: "AdditiveManufacturing",
            kind: "Classifier",
            specs: &["ManufacturingProcess"],
            domains: &["Manufacturing"],
            dim: None,
        },
        Row {
            name: "AssemblyProcess",
            kind: "Classifier",
            specs: &["ManufacturingProcess"],
            domains: &["Manufacturing"],
            dim: None,
        },
        Row {
            name: "JoiningProcess",
            kind: "Classifier",
            specs: &["ManufacturingProcess"],
            domains: &["Manufacturing"],
            dim: None,
        },
        Row {
            name: "FormingProcess",
            kind: "Classifier",
            specs: &["ManufacturingProcess"],
            domains: &["Manufacturing"],
            dim: None,
        },
        Row {
            name: "ModelArtifact",
            kind: "Classifier",
            specs: &["@os20/engineering#EngineeringThing"],
            domains: &["Design"],
            dim: None,
        },
        Row {
            name: "GeometryArtifact",
            kind: "Classifier",
            specs: &["ModelArtifact"],
            domains: &["Geometry"],
            dim: None,
        },
        Row {
            name: "BehaviorArtifact",
            kind: "Classifier",
            specs: &["ModelArtifact"],
            domains: &["Behaviour"],
            dim: None,
        },
        Row {
            name: "SimulationArtifact",
            kind: "Classifier",
            specs: &["ModelArtifact"],
            domains: &["Simulation"],
            dim: None,
        },
        Row {
            name: "TestArtifact",
            kind: "Classifier",
            specs: &["ModelArtifact"],
            domains: &["Verification"],
            dim: None,
        },
        Row {
            name: "DocumentationArtifact",
            kind: "Classifier",
            specs: &["ModelArtifact"],
            domains: &["Design"],
            dim: None,
        },
        Row {
            name: "SourceCodeArtifact",
            kind: "Classifier",
            specs: &["ModelArtifact"],
            domains: &["Behaviour"],
            dim: None,
        },
        Row {
            name: "EngineeringTool",
            kind: "Classifier",
            specs: &["@os20/engineering#EngineeringThing"],
            domains: &["Design"],
            dim: None,
        },
        Row {
            name: "CADTool",
            kind: "Classifier",
            specs: &["EngineeringTool"],
            domains: &["Geometry"],
            dim: None,
        },
        Row {
            name: "SimulationTool",
            kind: "Classifier",
            specs: &["EngineeringTool"],
            domains: &["Simulation"],
            dim: None,
        },
        Row {
            name: "SolverTool",
            kind: "Classifier",
            specs: &["EngineeringTool"],
            domains: &["Simulation"],
            dim: None,
        },
    ];
    graph("@os20/lifecycle", "Lifecycle.sysml", &rows, vec![])
}
